#@ load("@ytt:data", "data")

#@ for ns in data.values.workloads_ns:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini-namespaced-role
  namespace: #@ ns
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete

---
#! Bind to the default service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini-namespaced-rolebinding
  namespace: #@ ns
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: eirini-namespaced-role
subjects:
  - kind: ServiceAccount
    name: opi
    namespace: #@ data.values.system_ns

#@ end
