#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini-controller-namespaced-role
  namespace: #@ data.values.workloads_ns
rules:
  - apiGroups:
      - eirini.cloudfoundry.org
    resources:
      - lrps/status
    verbs:
      - update
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - update
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini-controller-namespaced-rolebinding
  namespace: #@ data.values.workloads_ns
roleRef:
  kind: Role
  name: eirini-controller-namespaced-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: eirini-controller
    namespace: #@ data.values.system_ns

