#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini-task-reporter-namespaced
  namespace: #@ data.values.workloads_ns
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - delete
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini-task-reporter-namespaced
  namespace: #@ data.values.workloads_ns
roleRef:
  kind: Role
  name: eirini-task-reporter-namespaced
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: eirini-task-reporter
    namespace: #@ data.values.system_ns
