---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eirini-task-reporter
  namespace: eirini-core

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini-task-reporter-psp
  namespace: eirini-core
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - eirini-task-reporter

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini-task-reporter-psp
  namespace: eirini-core
roleRef:
  kind: Role
  name: eirini-task-reporter-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eirini-task-reporter
  namespace: eirini-core

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: eirini-task-reporter
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'secret'
    - 'projected'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false

  # New thing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eirini-task-reporter
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eirini-task-reporter
roleRef:
  kind: ClusterRole
  name: eirini-task-reporter
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eirini-task-reporter
  namespace: eirini-core

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini-task-reporter-namespaced
  namespace: eirini-workloads
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - delete
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini-task-reporter-namespaced
  namespace: eirini-workloads
roleRef:
  kind: Role
  name: eirini-task-reporter-namespaced
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eirini-task-reporter
  namespace: eirini-core
