#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  name: eirini-api
  namespace: #@ data.values.system_ns
spec:
  ports:
    - port: 8085
      protocol: TCP
      name: https
  selector:
    name: eirini-api
