#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-api
  namespace: #@ data.values.system_ns
spec:
  selector:
    matchLabels:
      name: eirini-api
  template:
    metadata:
      labels:
        name: eirini-api
        eirinifs_version: v75.0.0
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: opi
      volumes:
        - name: config-map
          configMap:
            name: eirini
        - name: cc-certs
          secret:
            secretName: capi-tls
            optional: true
        - name: eirini-certs
          secret:
            secretName: eirini-certs
            optional: true
      securityContext:
        runAsNonRoot: true
      containers:
        - name: opi
          image: eirini/opi@sha256:e5315ef3fe28d8c0577db9b935764e81d20ffdb33a51c0c8bf0b553eecbbc20d
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-map
              mountPath: /etc/eirini/config
            - name: eirini-certs
              mountPath: /etc/eirini/certs
            - name: cc-certs
              mountPath: /etc/cf-api/certs
          ports:
            - containerPort: 8085
              name: https
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 100Mi
