#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  name: instance-index-env-injector
  namespace: #@ data.values.system_ns
spec:
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    name: instance-index-env-injector
