#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: task-reporter
  namespace: #@ data.values.system_ns
data:
  task-reporter.yml: |
    cc_tls_disabled: false
    completion_callback_retry_limit: 10
    ttl_seconds: 5
