#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-task-reporter
  namespace: #@ data.values.system_ns
spec:
  selector:
    matchLabels:
      name: eirini-task-reporter
  replicas: 2
  template:
    metadata:
      labels:
        name: eirini-task-reporter
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: eirini-task-reporter
      securityContext:
        runAsNonRoot: true
      containers:
        - name: task-reporter
          image: eirini/task-reporter@sha256:29defe5576b0f9633494deeecd3732ac7053534c511c22180c72e635443e9678
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 15m
              memory: 15Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: config-map-volume
              mountPath: /etc/eirini/config
            - name: cc-certs
              mountPath: /etc/cf-api/certs
      volumes:
        - name: config-map-volume
          configMap:
            name: task-reporter
            items:
              - key: task-reporter.yml
                path: task-reporter.yml
        - name: cc-certs
          secret:
            secretName: #@ data.values.capi_tls_secret_name
            optional: true
