---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eirini-metrics"
  namespace: "eirini-core"
spec:
  selector:
    matchLabels:
      name: "eirini-metrics"
  template:
    metadata:
      labels:
        name: "eirini-metrics"
    spec:
      dnsPolicy: "ClusterFirst"
      serviceAccountName: "eirini-metrics"
      volumes:
        - name: config-map-volume
          configMap:
            name: "eirini-metrics"
            items:
            - key: metrics.yml
              path: metrics.yml
        - name: loggregator-certs
          secret:
            secretName: loggregator-certs
            optional: true
      securityContext:
        runAsNonRoot: true
      containers:
      - name: metrics-collector
        image: eirini/metrics-collector@sha256:d99fcb5d7da00312aee0cad517a002ce8c9a7a23d425ba25267acc8dbacbd836
        imagePullPolicy: Always
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini-metrics/config
        - name: loggregator-certs
          mountPath: /etc/loggregator/certs
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 100m
            memory: 100Mi
