#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-event-reporter
  namespace: #@ data.values.system_ns
spec:
  selector:
    matchLabels:
      name: eirini-event-reporter
  replicas: 2
  template:
    metadata:
      labels:
        name: eirini-event-reporter
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: eirini-event-reporter
      volumes:
        - name: config-map-volume
          configMap:
            name: eirini-event-reporter
        - name: cc-certs
          secret:
            secretName: #@ data.values.capi_tls_secret_name
            optional: true
      securityContext:
        runAsNonRoot: true
      containers:
        - name: event-reporter
          image: eirini/event-reporter@sha256:638b2fd75cc74a6bf0aa1e4b0553234663b2c56ec7cc78485351c5f3a769ff01
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-map-volume
              mountPath: /etc/eirini-event-reporter/config
            - name: cc-certs
              mountPath: /etc/cf-api/certs
          resources:
            requests:
              cpu: 15m
              memory: 15Mi
            limits:
              cpu: 100m
              memory: 100Mi
