---
apiVersion: v1
kind: Service
metadata:
  name: eirini-environment-injector-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8083
      protocol: TCP
      name: https
  selector:
    name: "eirini-environment-injector"
