{{- if .Values.opi.staging.enable }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eirini-staging-reporter"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: "eirini-staging-reporter"
  template:
    metadata:
      labels:
        name: "eirini-staging-reporter"
    spec:
      dnsPolicy: "ClusterFirst"
      serviceAccountName: "eirini-staging-reporter"
      securityContext:
        runAsNonRoot: true
      containers:
      - name: staging-reporter
        {{- if .Values.opi.staging_reporter_image }}
        image: {{ .Values.opi.staging_reporter_image }}
        {{- else }}
        image: eirini/staging-reporter@sha256:6686f65f1c6e22620dc61e7bad939d80156a3f2258069a5a3e597d7574d5f662
        {{- end }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: {{ .Values.kube.resources.staging.requests.cpu }}
            memory: {{ .Values.kube.resources.staging.requests.memory }}
          limits:
            cpu: {{ .Values.kube.resources.staging.limits.cpu }}
            memory: {{ .Values.kube.resources.staging.limits.memory }}
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini/config
        - name: cf-secrets
          mountPath: /etc/eirini/secrets
      volumes:
        - name: config-map-volume
          configMap:
            name: "eirini"
            items:
            - key: staging-reporter.yml
              path: staging-reporter.yml
        - name: cf-secrets
          projected:
            sources:
            - secret:
                name: "{{ .Values.opi.staging.tls.stagingReporter.secretName }}"
                items:
                - key: "{{ .Values.opi.staging.tls.stagingReporter.certPath }}"
                  path: eirini-client.crt
                - key: "{{ .Values.opi.staging.tls.stagingReporter.keyPath }}"
                  path: eirini-client.key
                - key: "{{ .Values.opi.staging.tls.stagingReporter.caPath }}"
                  path: eirini-client.ca
            - secret:
                name: "{{ .Values.opi.events.tls.capi.secretName }}"
                items:
                - key: "{{ .Values.opi.events.tls.capi.caPath }}"
                  path: cc.ca
{{- end }}
