{{- if .Values.opi.tasks.enable }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eirini-task-reporter"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: "eirini-task-reporter"
  template:
    metadata:
      labels:
        name: "eirini-task-reporter"
    spec:
      dnsPolicy: "ClusterFirst"
      serviceAccountName: "eirini-task-reporter"
      securityContext:
        runAsNonRoot: true
      containers:
      - name: task-reporter
        {{- if .Values.opi.task_reporter_image }}
        image: {{ .Values.opi.task_reporter_image }}
        {{- else }}
        image: eirini/task-reporter@sha256:d61740f4ab2b6717748c4aaaf53c6d00363853c426cabefeec25494e068b6138
        {{- end }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: {{ .Values.kube.resources.task_reporter.requests.cpu }}
            memory: {{ .Values.kube.resources.task_reporter.requests.memory }}
          limits:
            cpu: {{ .Values.kube.resources.task_reporter.limits.cpu }}
            memory: {{ .Values.kube.resources.task_reporter.limits.memory }}
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini/config
        {{- if not .Values.opi.cc_api.tls_disabled }}
        - name: cf-secrets
          mountPath: /etc/eirini/secrets
        {{- end }}
      volumes:
        - name: config-map-volume
          configMap:
            name: "eirini"
            items:
            - key: task-reporter.yml
              path: task-reporter.yml
        {{- if not .Values.opi.cc_api.tls_disabled }}
        - name: cf-secrets
          secret:
             secretName: "{{ .Values.opi.tasks.tls.taskReporter.secretName }}"
             items:
             - key: "{{ .Values.opi.tasks.tls.taskReporter.certPath }}"
               path: cc.crt
             - key: "{{ .Values.opi.tasks.tls.taskReporter.keyPath }}"
               path: cc.key
             - key: "{{ .Values.opi.tasks.tls.taskReporter.caPath }}"
               path: cc.ca
        {{- end }}
{{- end }}
