#@ load("@ytt:data", "data")

#@ for ns in data.values.workloads_ns:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini-event-reporter-namespaced
  namespace: #@ ns
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini-event-reporter-namespaced
  namespace: #@ ns
roleRef:
  kind: Role
  name: eirini-event-reporter-namespaced
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: eirini-event-reporter
    namespace: #@ data.values.system_ns
#@ end
