---
apiVersion: v1
kind: Service
metadata:
  name: cc-wiremock
  namespace: eirini-core
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8081
      protocol: TCP
      name: https
  selector:
    name: cc-wiremock
